# // keys
# remap the keys
unbind C-b
set -g prefix C-a
bind a send-prefix

# set keys to vi settings
setw -g mode-keys vi

# pane selection with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane rezise with vim keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# pane switching with alt + vim keys
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# new panes
bind | split-window -h
bind _ split-window -v

# remove keydelay
set -sg escape-time 1

# reload config file
bind-key r source-file ~/.tmux.conf

# // terminal settings
set -g default-terminal "screen-256color"

# set history
set -g history-limit 100000

# start with window uno
set -g base-index 1
# reload statusline each 5 seconds
set -g status-interval 5

# // colors
# panes passive and active
set -g pane-border-style bg=colour0
set -g pane-border-style fg=colour8
set -g pane-active-border-style bg=colour0
set -g pane-active-border-style fg=colour208

# statusbar left
set -g status-left-length 100
set -g status-left "#h : #(ip addr show dev eth0 | grep "inet[^6]" | awk '{print $2}')"


# statusbar center
set -g status-position bottom
set -g status-fg colour0

# set color of active/inactive pane
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'
