#!/usr/bin/bash

prompt_user() {
    while true; do
        if [[ $1 == "skip" ]]; then 
            read -p "Skip all downloads and installs? [y/n] " yn
        else
            read -p "Do you want to install the program $1? [y/n] " yn
        fi
    # read the response
    case $yn in
        [Yy]* ) result=0; break;;
        [Nn]* ) result=1; break;;
        * ) echo "Please answer yes or no.";;
    esac
done
return $result
}

install_apt_packages() {
    echo "...installing apt packages!"
    sudo apt-get update 
    packages="tmux fzf bat ripgrep tldr tree xsel jq btop python-is-python3 zsh-autosuggestions"
    sudo apt-get install $packages -y
    tldr -u > /dev/null
}

install_ohmyzsh() {
    prompt_user "zsh"
    if [[ $? == 1 ]]; then return; fi
    $(which bash) -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc > /dev/null
}

install_nvim() {
    # first install neovim
    prompt_user "nvim and plugins"
    if [[ $? == 1 ]]; then return; fi
    sudo add-apt-repository ppa:neovim-ppa/stable -y && sudo apt-get update && sudo apt-get install neovim -y
    # install vimplug
    sh -c 'curl -s -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    # install the plugins
    /usr/bin/nvim -E +PlugInstall +qall
}

install_other_packages() {
    prompt_user "thefck";   if [[ $? == 0 ]]; then pip3 install thefuck --user --no-warn-script-location; fi;
    prompt_user "autojump"; if [[ $? == 0 ]]; then 
        git clone https://github.com/wting/autojump /tmp/autojump && cd /tmp/autojump && python3 ./install.py
    fi
}

create_symlinks() {
    # symlink the the theme for ohmyzsh
    ln -sf $HOME/.config/zsh/kevinjel.zsh-theme $HOME/.oh-my-zsh/themes/kevinjel.zsh-theme
    ln -sf $HOME/.config/git/gitconfig $HOME/.gitconfig
    ln -sf $HOME/.config/nvim/init.vim $HOME/.vimrc
}


prompt_user "skip"
if [[ $? == 1 ]]; then
    install_apt_packages
    echo "...be very careful with what you autodownload/install from the web!"
    install_ohmyzsh
    install_nvim
    install_other_packages
fi
create_symlinks

echo "...done bootstrapping"
