#!/usr/bin/bash

prompt_user() {
    while true; do
        if [[ $1 == "skip" ]]; then 
            read -p "Is this a non-install run? [y/n] " yn
        else
            read -p "Do you want to install the program $1? [y/n] " yn
        fi
    # read the response
    case $yn in
        [Yy]* ) result=0; break;;
        [Nn]* ) result=1; break;;
        * ) echo "Please answer yes or no.";;
    esac
done
return $result
}

install_ohmyzsh() {
    prompt_user "zsh"
    if [[ $? == 1 ]]; then return; fi
    $(which bash) -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

install_vim-plug() {
    prompt_user "vim-plug"
    if [[ $? == 1 ]]; then return; fi
    sh -c 'curl -s -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
}

install_apt_packages() {
    echo "...installing apt packages!"
    packages="tmux fzf bat ripgrep tldr tree xsel jq"
    sudo apt-get install $packages -y
    tldr -u
}

install_other_packages() {
    prompt_user "thefck";   if [[ $? == 0 ]]; then pip3 install thefuck --user; fi;
    prompt_user "debt-get"; if [[ $? == 0 ]]; then
        curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
    fi
}

create_symlinks() {
    # symlink the the theme for ohmyzsh
    ln -sf $HOME/.config/zsh/kevinjel.zsh-theme $HOME/.oh-my-zsh/themes/kevinjel.zsh-theme
    ln -sf $HOME/.config/git/gitconfig $HOME/.gitconfig
    ln -sf $HOME/.config/nvim/init.vim $HOME/.vimrc
}


prompt_user "skip"
if [[ $? == 1 ]]; then
    echo "...be very careful with what you autodownload/install from the web!"
    install_ohmyzsh
    install_vim-plug
    install_other_packages
    install_apt_packages
fi
create_symlinks

echo "...done bootstrapping"
