# // keys
# remap the keys
unbind C-b
set -g prefix C-a
bind a send-prefix

# set keys to vi settings
setw -g mode-keys vi

# pane selection with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane rezise with vim keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# pane switching with alt + vim keys
# inactive since we use these keys to jump words within terminal
#bind -n M-h select-pane -L
#bind -n M-j select-pane -D
#bind -n M-k select-pane -U
#bind -n M-l select-pane -R

# new panes
bind | split-window -h
bind _ split-window -v

# set ctrl-a + Q to show the panenr for 3 seconds
set -g display-panes-time 3000
# remove keydelay
set -sg escape-time 1
setw -g monitor-activity on
set -g visual-activity on

# reload config file
bind-key r source-file ~/.tmux.conf

# // terminal settings
set -g default-terminal "screen-256color"

# set history
set -g history-limit 100000

# start with window uno
set -g base-index 1
# reload statusline each 5 seconds
set -g status-interval 5

# // colors
# panes passive and active (borders)
set -g pane-border-style bg=colour236
set -g pane-border-style fg=colour8
set -g pane-active-border-style bg=colour236
set -g pane-active-border-style fg=colour208

# status bars
set -g status-style bg=colour208
setw -g window-status-current-style bg=colour236
setw -g window-status-current-style fg=colour236
# left
set -g status-left '#[bg=colour236,fg=colour246] [#[fg=colour231]#S#[fg=colour246]] #[default]'
set -g status-left-length 50
# right
set -g status-right " %H:%M %d-%b-%y "
setw -g status-right-style fg=colour236
setw -g window-status-format " #I:#{?window_flags,#{window_flags},}#W "
setw -g window-status-current-format " #I:#{?window_flags,#{window_flags},}#W "

# set color of active/inactive pane
setw -g window-active-style 'fg=colour254,bold'
setw -g window-style 'fg=colour243,dim'

# enable mousemode
set -g mouse on

# set default shell to zsh...
set-option -g default-shell $SHELL

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
